security:
    encoders:
        IBM\MTMBundle\Entity\Users:
          algorithm: bcrypt
          cost: 15

    role_hierarchy:
        ROLE_CUSTOMER: [ROLE_USER]
        ROLE_ADMIN: [ROLE_USER]

    providers:
        users:
            entity: { class: "IBMMTMBundle:Users", property: username }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/login$
            security: false
            
        recover:
            pattern: ^/forgot$
            security: false

        secured_area:
            pattern:    ^/
            form_login:
                check_path: login_check
                login_path: login
            logout:
                path:   logout
                target: /
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/forgot, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/atm, roles: ROLE_CUSTOMER, requires_channel: https }
        - { path: ^/, roles: ROLE_ADMIN, requires_channel: https }
