parameters:
    ibmmtm.customerservice.class: IBM\MTMBundle\Services\CustomerService

services:
    ibmmtm.customerservice:
        class: "%ibmmtm.customerservice.class%"
        arguments: ["@doctrine.orm.entity_manager", "@session", "@templating", "@form.factory", "@router"]
        
    ibmmtm.form.type.customer:
        class: IBM\MTMBundle\Form\CustomerType
        tags:
            - { name: form.type, alias: customer_type }
