IBM\MTMBundle\Entity\Balance:
    type: entity
    table: BALANCE
    id:
        account:
            column: ACCT
            type: string
            length: 12
            nullable: false
            id: true
    fields:
        balance:
            column: BALANCE
            type: decimal
            precision: 7
            scale: 2
            nullable: false
    oneToOne:
        customer:
            targetEntity: Customer
            inversedBy: balance
            joinColumn:
               name: acct
               referencedColumnName: ACCT 
    lifecycleCallbacks: {  }
