IBM\MTMBundle\Entity\Trans:
    type: entity
    table: TRANS
    id:
        id:
            column: ID
            type: integer
            nullable: false
            unsigned: false
            generator:
               strategy: IDENTITY
    fields:
        account:
            column: ACCT
            type: string
            length: 12
            nullable: false
        amount:
            column: AMOUNT
            type: decimal
            precision: 7
            scale: 2
            nullable: false
        type:
            column: TRNTYPE
            type: string
            length: 1
            nullable: false
        timeStart:
            column: TIME_START
            type: datetime
            nullable: false
        timeEnd:
            column: TIME_END
            type: datetime
            nullable: false
    manyToOne:
        customer:
            targetEntity: Customer
            joinColumn:
               name: ACCT
               referencedColumnName: ACCT 
    lifecycleCallbacks: { }
