IBM\MTMBundle\Entity\Users:
    type: entity
    table: USERS
    uniqueConstraints:
        username_UNIQUE:
            columns:
                - username
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        username:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        password:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        salt:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        email:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        role:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
