atm:
    pattern:  /
    defaults: { _controller: "IBMMTMBundle:ATM:index" }
    
transaction:
    pattern:  /transaction
    defaults: { _controller: "IBMMTMBundle:ATM:transaction" }
    requirements:
      _method: POST